# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-20 18:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_login', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='last_namename',
            new_name='last_name',
        ),
    ]
