# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-21 15:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_authors', '0002_auto_20171120_2351'),
    ]

    operations = [
        migrations.AddField(
            model_name='authors',
            name='books',
            field=models.ManyToManyField(related_name='authors', to='book_authors.Book'),
        ),
        migrations.AddField(
            model_name='authors',
            name='notes',
            field=models.TextField(default='hello'),
            preserve_default=False,
        ),
    ]
